library_app/urls.py
from django.urls import path
from . import views

app_name = 'library_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('loan_book/', views.loan_book, name="loan_book"),
    path('inventory/', views.inventory, name="inventory"),
    path('delete_book/', views.delete_book, name="delete_book"),
    path('add_book/', views.add_book, name="add_book"),
    path('return_book/', views.return_book, name="return_book"),
    path('loan_magazine/', views.loan_magazine, name="loan_magazine"),
    path('delete_magazine/', views.delete_magazine, name="delete_magazine"),
    path('add_magazine/', views.add_magazine, name="add_magazine"),
    path('return_magazine/', views.return_magazine, name="return_magazine"),
    path('list_of_checkouts/', views.list_of_checkouts, name="list_of_checkouts"),
]

libraryproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', include('library_app.urls')),
    path('accounts/', include('login_app.urls')),
]

login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('request_password_reset/', views.request_password_reset, name='request_password_reset'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('delete_account/', views.delete_account, name='delete_account'),
    path('change_password/', views.change_password, name='change_password'),
]

library_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Book(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    author = models.CharField(max_length=200)
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=500)
    loan_date = models.DateTimeField(auto_now=True, null=True, blank=True)
    status = models.BooleanField(default=False)


    def __str__(self):
        return f"{self.title, self.status}"


class Magazine(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=500)
    loan_date = models.DateTimeField(auto_now=True, null=True, blank=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title, self.status}"

library_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from datetime import timedelta, datetime
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

from .models import Book, Magazine


# Create your views here.


def index(request):
    books = Book.objects.filter(status=False)
    book_count = Book.objects.filter(status=False).count()
    magazines = Magazine.objects.filter(status=False)
    magazine_count = Magazine.objects.filter(status=False).count()
    context = {
        'books': books,
        'magazines': magazines,
        'book_counter': book_count,
        'magazine_counter': magazine_count
    }

    return render(request, 'library_app/index.html', context)

@login_required
def inventory(request):
    books = Book.objects.filter(user=request.user, status=True)
    book_count = Book.objects.filter(user=request.user, status=True).count()
    magazines = Magazine.objects.filter(user=request.user, status=True)
    magazine_count = Magazine.objects.filter(user=request.user, status=True).count()

    context = {
        'books': books,
        'magazines': magazines,
        'book_counter': book_count,
        'magazine_counter': magazine_count
    }
    return render(request, 'library_app/inventory.html', context)

@staff_member_required
def list_of_checkouts(request):
    date_30_days = datetime.now() + timedelta(days=30)
    books = Book.objects.filter(loan_date__gt=date_30_days)
    date_7_days = datetime.now() + timedelta(days=7)
    magazines = Magazine.objects.filter(loan_date__gt=date_7_days)
    context = {
        'books': books,
        'magazines': magazines
    }
    return render(request, 'library_app/list_of_checkouts.html', context)

@login_required
def loan_book(request):
    amount_of_books = Book.objects.filter(user=request.user).count()
    if amount_of_books < 10:
        pk = request.POST["pk"]
        book = get_object_or_404(Book, pk=pk)
        book.status = True
        book.user = request.user
        book.loan_date = datetime.now()
        print(book.user, book.loan_date)
        book.save()
        return HttpResponseRedirect(reverse('library_app:inventory'))
    else:
        books = Book.objects.filter(status=False)
        book_count = Book.objects.filter(status=False).count()
        magazines = Magazine.objects.all()
        context = {
            'error': 'No more than 10 books, please return some books',
            'books': books,
            'magazines': magazines,
            'book_counter': book_count
        }
    return render(request, 'library_app/index.html', context)

@login_required
def loan_magazine(request):
    amount_of_magazines = Magazine.objects.filter(user=request.user).count()
    if amount_of_magazines < 7:
        pk = request.POST["pk"]
        magazine = get_object_or_404(Magazine, pk=pk)
        magazine.status = True
        magazine.user = request.user
        magazine.loan_date = datetime.now()
        print(magazine.user, magazine.loan_date)
        magazine.save()
        return HttpResponseRedirect(reverse('library_app:inventory'))
    else:
        magazines = Magazine.objects.filter(status=False)
        magazine_count = Magazine.objects.filter(status=False).count()
        books = Book.objects.all()
        context = {
            'error': 'No more than 7 magazines, please return some magazines',
            'magazines': magazines,
            'books': books,
            'magazine_counter': magazine_count
        }
    return render(request, 'library_app/index.html', context)

@login_required
def return_book(request):
    pk = request.POST["pk"]
    book = get_object_or_404(Book, pk=pk)
    book.status = False
    book.loan_date = None
    book.user = None
    print(book.loan_date, book.user)
    book.save()
    return HttpResponseRedirect(reverse('library_app:inventory'))

@login_required
def return_magazine(request):
    pk = request.POST["pk"]
    magazine = get_object_or_404(Magazine, pk=pk)
    magazine.status = False
    magazine.loan_date = None
    magazine.user = None
    print(magazine.loan_date, magazine.user)
    magazine.save()
    return HttpResponseRedirect(reverse('library_app:inventory'))

@staff_member_required
def add_book(request):
    if request.method == "POST":
        title = request.POST["title"]
        author = request.POST["author"]
        description = request.POST["description"]
        book = Book()
        book.title = title
        book.author = author
        book.description = description
        print(book.user, book.loan_date)
        book.save()
        return HttpResponseRedirect(reverse('library_app:index'))
    return render(request, 'library_app/add_book.html')

@staff_member_required
def add_magazine(request):
    if request.method == "POST":
        title = request.POST["title"]
        description = request.POST["description"]
        magazine = Magazine()
        magazine.title = title
        magazine.description = description
        print(magazine.user, magazine.loan_date)
        magazine.save()
        return HttpResponseRedirect(reverse('library_app:index'))
    return render(request, 'library_app/add_magazine.html')

@staff_member_required
def delete_book(request):
    pk = request.POST["pk"]
    book = get_object_or_404(Book, pk=pk)
    book.delete()
    return HttpResponseRedirect(reverse('library_app:index'))

@staff_member_required
def delete_magazine(request):
    pk = request.POST["pk"]
    magazine = get_object_or_404(Magazine, pk=pk)
    magazine.delete()
    return HttpResponseRedirect(reverse('library_app:index'))

library_app/templates/library_app/add_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Book</title>
</head>
<body>
    <h1>Add Book</h1>
    <div>
        <form action="{% url 'library_app:add_book' %}" method="POST">
            {% csrf_token %}
            <input name="author" type="text" placeholder="Author...">
            <input name="title" type="text" placeholder="Title...">
            <input name="description" type="text" placeholder="Description...">
            <button>Add book</button>
        </form>
    </div>
</body>
</html>

library_app/templates/library_app/add_magazine.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Magazine</title>
</head>
<body>
    <h1>Add magazine</h1>
    <div>
        <form action="{% url 'library_app:add_magazine' %}" method="POST">
            {% csrf_token %}
            <input name="title" type="text" placeholder="Title...">
            <input name="description" type="text" placeholder="Description...">
            <button>Add magazine</button>
        </form>
    </div>
</body>
</html>

library_app/templates/library_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All books and magazines</title>
</head>
<body>
    <h1>Library - books and magazines</h1>
    <h2>Welcome {{user.username}}</h2>
    {% if user.is_staff %}<a href="{% url 'library_app:add_book' %}">Add book</a>{% endif %}
    {% if user.is_staff %}<a href="{% url 'library_app:add_magazine' %}">Add magazine</a>{% endif %}
    <a href="{% url 'library_app:inventory' %}">Inventory</a>
    {% if user.is_staff %}<a href="{% url 'library_app:list_of_checkouts' %}">List of Checkouts</a>{% endif %}
    <a href="{% url 'login_app:logout' %}">Logout</a>
    <a href="{% url 'login_app:change_password' %}">Change password</a>
    <a href="{% url 'login_app:delete_account' %}">Delete account</a>


    <h3>    
        {% if error %}
            {{ error }}
        {% endif %}
    </h3>
    <hr />

    <h2>Books: {{book_counter}}</h2>
    
    <div>
    {% for book in books %}
    <hr />
        <div>Title: {{book.title}}</div>
        <div>Author: {{book.author}}</div>    
        <div>Description: {{book.description}}</div>

        <form action="{% url 'library_app:loan_book' %}" method="POST">
            {% csrf_token %}
            <button>Loan</button>
            {% if user.is_staff %}<button formaction="{% url 'library_app:delete_book' %}">Delete</button>{% endif %}
            <input type="hidden" name="pk" value="{{ book.pk }}">
        </form>

        

    <hr />
    {% endfor %}
    </div>
    <hr />

    <h2>Magazines: {{magazine_counter}}</h2>
    <div>
    {% for magazine in magazines %}
    <hr />
        <div>Title: {{magazine.title}}</div>
        <div>Description {{magazine.description}}</div>

        <form action="{% url 'library_app:loan_magazine' %}" method="POST">
            {% csrf_token %}
            <button>Loan</button>
            {% if user.is_staff %}<button formaction="{% url 'library_app:delete_magazine' %}">Delete</button>{% endif %}
            <input type="hidden" name="pk" value="{{ magazine.pk }}">
        </form>
    <hr />
    {% endfor %}
    <div>  
    <hr />
</body>
</html>

library_app/templates/library_app/inventory.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inventory</title>
</head>
<body>
    <h1>Inventory</h1>
    <a href="{% url 'library_app:index' %}">See library</a>
    <a href="{% url 'login_app:logout' %}">Logout</a>
    <a href="{% url 'login_app:change_password' %}">Change password</a>
    <a href="{% url 'login_app:delete_account' %}">Delete account</a>
    
    <hr />
    <h2>Books: {{book_counter}}</h2>
    <div>
    {% for book in books %}
    <hr />
        <div>Title: {{book.title}}</div>
        <div>Author: {{book.author}}</div>    
        <div>Description: {{book.description}}</div>

        <form action="{% url 'library_app:return_book' %}" method="POST">
            {% csrf_token %}
            <button>Return</button>
            <input type="hidden" name="pk" value="{{ book.pk }}">
        </form>

    <hr />
    {% endfor %}
    </div>
    <hr />

    <h2>Magazines: {{magazine_counter}}</h2>
    <div>
    {% for magazine in magazines %}
    <hr />
        <div>Title: {{magazine.title}}</div>
        <div>Description {{magazine.description}}</div>

        <form action="{% url 'library_app:return_magazine' %}" method="POST">
            {% csrf_token %}
            <button>Return</button>
            <input type="hidden" name="pk" value="{{ magazine.pk }}">
        </form>
    <hr />
    {% endfor %}
    <div>  
    <hr />
</body>
</html>

library_app/templates/library_app/list_of_checkouts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List of Checkouts</title>
</head>
<body>
    <h1>List of Checkouts</h1>
    <a href="{% url 'library_app:add_book' %}">Add book</a>
    <a href="{% url 'library_app:inventory' %}">Inventory</a>


    <hr />
    <h2>Books:</h2>
    <div>
    {% for book in books %}
    <hr />
        <div>Title: {{book.title}}</div>
        <div>Author: {{book.author}}</div>    
        <div>Description: {{book.description}}</div>
        <div>Description: {{book.user}}</div>

    <hr />
    {% endfor %}
    </div>
    <hr />

    <h2>Magazines:</h2>
    <div>
    {% for magazine in magazines %}
    <hr />
        <div>Title: {{magazine.title}}</div>
        <div>Description {{magazine.description}}</div>
    <hr />
    {% endfor %}
    <div>  
    <hr />
</body>
</html>