libraryproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', include('library_app.urls')),
    path('accounts/', include('login_app.urls')),
]

login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('request_password_reset/', views.request_password_reset, name='request_password_reset'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('delete_account/', views.delete_account, name='delete_account'),
    path('change_password/', views.change_password, name='change_password'),
]

login_app/models.py
from django.db import models
from django.contrib.auth.models import User
from secrets import token_urlsafe


class PasswordResetRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=43, default=token_urlsafe)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    updated_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user} - {self.created_timestamp} - {self.updated_timestamp} - {self.token}'

login_app/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import HttpResponseRedirect
from . models import PasswordResetRequest
from django.contrib.auth.decorators import login_required


def login(request):
    context = {}

    if request.method == "POST":
        user = authenticate(request, username=request.POST['user'], password=request.POST['password'])
        if user:
            dj_login(request, user)
            return HttpResponseRedirect(reverse('library_app:index'))
        else:
            context = {
                'error': 'Bad username or password.'
            }
    return render(request, 'login_app/login.html', context)


def logout(request):
    dj_logout(request)
    return render(request, 'login_app/login.html')


def request_password_reset(request):
    if request.method == "POST":
        post_user = request.POST['username']
        user = None

        if post_user:
            try:
                user = User.objects.get(username=post_user)
            except:
                print(f"Invalid password request: {post_user}")
        else:
            post_user = request.POST['email']
            try:
                user = User.objects.get(email=post_user)
            except:
                print(f"Invalid password request: {post_user}")
        if user:
            prr = PasswordResetRequest()
            prr.user = user
            prr.save()
            print(prr)
            return HttpResponseRedirect(reverse('login_app:password_reset'))

    return render(request, 'login_app/request_password_reset.html')

def change_password(request):
    if request.method == "POST":
        user = User.objects.get(id=request.user.id)
        password = request.POST['password']
        user.set_password(password)
        user.save()
        return HttpResponseRedirect(reverse('login_app:logout'))
    return render(request, 'login_app/change_password.html')



def password_reset(request):
    if request.method == "POST":
        post_user = request.POST['username']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        token = request.POST['token']

        if password == confirm_password:
            try:
                prr = PasswordResetRequest.objects.get(token=token)
                prr.save()
            except:
                print("Invalid password reset attempt.")
                return render(request, 'login_app/password_reset.html')
                
            user = prr.user
            user.set_password(password)
            user.save()

            return HttpResponseRedirect(reverse('login_app:login'))

    return render(request, 'login_app/password_reset.html')


def sign_up(request):
    context = {}
    if request.method == "POST":
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        user_name = request.POST['user']
        email = request.POST['email']
        
        if password == confirm_password:
            if "checked" in request.POST:
                if User.objects.create_user(user_name, email, password, is_staff=True):
                    return HttpResponseRedirect(reverse('login_app:login'))
            elif User.objects.create_user(user_name, email, password):
                    return HttpResponseRedirect(reverse('login_app:login'))
            else:
                context = {
                    'error': 'Could not create user account - please try again.'
                }
        else:
            context = {
                'error': 'Passwords did not match. Please try again.'
            }
    return render(request, 'login_app/sign_up.html', context)
    

@login_required
def delete_account(request):
    if request.method == "POST":
        if request.POST['confirm_deletion'] == "DELETE":            
            user = authenticate(request, username=request.user.username, password=request.POST['password'])
            if user:
                print(f"Deleting user {user}")
                user.delete()
                return HttpResponseRedirect(reverse('login_app:login'))
            else:
                print("fail delete")

    return render(request, 'login_app/delete_account.html')

login_app/templates/login_app/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Password</title>
</head>
<body>
    <h1>Reset Password</h1>
    <hr />
    <form action="{% url 'login_app:change_password' %}" method="POST">
        {% csrf_token %}
        <input type="password" name="password" placeholder="New Password">
        <br />
        <input type="password" name="confirm_password" placeholder="Repeat New Password">
        <br />
        <button>Submit</button>
    </form>
    <hr />
</body>
</html>

login_app/templates/login_app/delete_account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Account</title>
</head>
<body>
    <h1>Delete Account</h1>
    <hr />
    <form action="{% url 'login_app:delete_account'%}" method="POST">
        {% csrf_token %}
        <input type="password" name="password" placeholder="Password">
        <br />
        <input type="text" name="confirm_deletion" placeholder="TYPE DELETE">
        <br />
        <button>Submit</button>
    </form>
    <hr />    
</body>
</html>

login_app/templates/login_app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    <a href="{% url 'login_app:sign_up' %}">Sign Up</a>
    <hr />
        <form action="{% url 'login_app:login' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="user" placeholder="User Name">
            <input type="password" name="password" placeholder="Password">
            <button>Login</button>
        </form>
    <hr />
    {% if error %}
        {{ error }}
    {% endif %}
    <br />
    {% comment %} <a href="{% url 'login_app:request_password_reset' %}">Request Password Reset</a> {% endcomment %}
</body>
</html>

login_app/templates/login_app/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Password</title>
</head>
<body>
    <h1>Reset Password</h1>
    <h3>Your Token: {{prr.token}}</h3>
    <hr />
    <form action="{% url 'login_app:password_reset' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="User Name">
        <br />
        <input type="password" name="password" placeholder="New Password">
        <br />
        <input type="password" name="confirm_password" placeholder="Repeat New Password">
        <br />
        <input type="text" name="token" placeholder="Token">
        <br />
        <button>Submit</button>
    </form>
    <hr />
</body>
</html>

login_app/templates/login_app/request_password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Request Password Reset</title>
</head>
<body>
    <h1>Request Password Reset</h1>
    <hr />
        <form action="{% url 'login_app:request_password_reset' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="username" placeholder="User Name">
            <br />
            <input type="email" name="email" placeholder="Email Address">
            <br />
            <button>Submit</button>
        </form>
    <hr />    
</body>
</html>

login_app/templates/login_app/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
</head>
<body>
    <h1>Sign Up</h1>
    <hr />
    <form action="{% url 'login_app:sign_up' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="user" placeholder="User Name">
        <input type="email" name="email" placeholder="Email Address">
        <input type="password" name="password" placeholder="Password">
        <input type="password" name="confirm_password" placeholder="Confirm Password">
        <input type="checkbox" name="checked">
        <label for="checked">Staff</label>
        <button>Sign Up</button>
    </form>
    <hr />
    {% if error %}
        {{ error }}
    {% endif %}
</body>
</html>